apiVersion: v1
kind: Service
metadata:
  name: text-analyzer-api-service
spec:
  type: NodePort
  selector:
    app: text-analyzer-api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30080